class DataFile
  
  # Thanks ChatGpt for providing names for me, despite resisting and trying to convonce me to use Faker

  $male_names = [
  "Adam", "Aiden", "Alex", "Alexander", "Andrew", "Anthony", "Archer", "Asher", "Benjamin", "Caleb", "Cameron",
  "Carter", "Charles", "Christopher", "Daniel", "David", "Declan", "Dominic", "Eli", "Elias", "Elijah", "Eliott",
  "Emmett", "Ethan", "Everett", "Felix", "Gabriel", "George", "Henry", "Hudson", "Hunter", "Isaac", "Jack", "Jackson",
  "Jacob", "James", "Jason", "John", "Jonathan", "Joseph", "Joshua", "Josiah", "Julian", "Kaden", "Landon", "Leo",
  "Liam", "Lincoln", "Logan", "Lucas", "Mason", "Matthew", "Maxwell", "Michael", "Nathan", "Nicholas", "Noah", "Oliver",
  "Oscar", "Owen", "Patrick", "Samuel", "Sebastian", "Theodore", "Thomas", "Tristan", "Victor", "William", "Wyatt",
  "Xander", "Zachary", "Zane", "Aleksandr", "Andrey", "Antono", "Artem", "Dmitri", "Fedor", "Ivan", "Kirill",
  "Konstantin", "Maksim", "Mikhail", "Nikita", "Nikolay", "Pavel", "Sergey", "Stanislav", "Vadim", "Viktor", "Vladimir",
  "Yurio", "Aleksandr", "Alexei", "Anatoli", "Andrei", "Anton", "Arkadi", "Boris", "Dmitrii", "Evgenii", "Fyodor",
  "Grigori", "Igor", "Ilya", "Leonid", "Mikhail", "Nikolai", "Pavelo", "Pyotr", "Sergei", "Viktorn", "Vladimiro", "Yuriis",
  "Yuriy", "Yury"
]

  $female_names = [
    "Magdalina", "Abigail", "Ada", "Adriana", "Aisha", "Alejandra", "Alexandra", "Alice", "Alina", "Alicia", "Amelia", "Ana",
    "Anastasia", "Angelina", "Anna", "Annabelle", "Aria", "Ariana", "Aurora", "Ava", "Bella", "Brianna", "Camila",
    "Caroline", "Charlotte", "Chloe", "Clara", "Cora", "Daisy", "Eleanor", "Elena", "Eliza", "Elizabeth", "Ella",
    "Emilia", "Emily", "Emma", "Eva", "Evelyn", "Faith", "Fiona", "Gabriela", "Grace", "Hannah", "Harper", "Hazel",
    "Isabella", "Ivy", "Jasmine", "Josephine", "Julia", "Katherine", "Layla", "Leah", "Lena", "Lillian", "Lily", "Luna",
    "Lydia", "Mackenzie", "Madeline", "Madison", "Makayla", "Mila", "Natalie", "Nora", "Olivia", "Paisley", "Penelope",
    "Piper", "Riley", "Ruby", "Samantha", "Savannah", "Scarlett", "Serenity", "Sofia", "Sophia", "Sophie", "Stella",
    "Valentina", "Victoria", "Violet", "Zoe", "Anastasia", "Daria", "Ekaterina", "Elena", "Elizaveta", "Galina", "Irina",
    "Ksenia", "Larisa", "Ludmila", "Margarita", "Maria", "Nadezhda", "Natalia", "Olga", "Polina", "Svetlana", "Tatiana",
    "Valentina", "Varvara", "Vera", "Veronika", "Viktoria", "Yelena", "Aaliyah", "Adalynn", "Adele", "Adrienne", "Alexia",
    "Aliyah", "Amelie", "Angelica", "Arabella", "Beatrice", "Bianca", "Camille", "Catalina", "Cecilia", "Celeste",
    "Delilah", "Evangeline", "Francesca", "Genevieve", "Gianna", "Guinevere", "Haven", "Imogen", "Isabeau", "Jocelyn",
    "Kamila", "Karina", "Katrina", "Leonora", "Liliana", "Luciana", "Luz", "Mallory", "Margot", "Marina", "Melody",
    "Miranda", "Nadia", "Nayeli", "Noelle", "Ophelia", "Rosalie", "Seraphina", "Sienna", "Sylvia", "Talia", "Viviana",
    "Wren", "Zara"
]

  $conversational_phrases = [
    "How's it going?",
    "What's up?",
    "Nice weather we're having, isn't it?",
    "How was your day?",
    "What are your plans for the weekend?",
    "I'm sorry to hear that.",
    "Congratulations on your success!",
    "I appreciate your help.",
    "Could you please pass the salt?",
    "I'm really looking forward to it.",
    "How's your family doing?",
    "Have you been on any vacations recently?",
    "Do you have any recommendations for a good restaurant?",
    "I can't believe it's already Friday!",
    "What's your favorite book?",
    "I'm feeling a bit under the weather.",
    "Thank you for your time and effort.",
    "It's a pleasure to meet you.",
    "I completely understand.",
    "What's your favorite type of music?",
    "I'll be there in a few minutes.",
    "How's your job going?",
    "What's your favorite movie?",
    "I'm not sure about that.",
    "Can you help me with this?",
    "Let's catch up soon!",
    "I hope you have a great day!",
    "What's your favorite hobby?",
    "What do you like to do in your free time?",
    "I'm here if you need anything.",
    "How's your pet doing?",
    "I had a wonderful weekend.",
    "I'd love to hear more about it.",
    "I'm feeling much better now.",
    "I had a fantastic time last night.",
    "How's your new project coming along?",
    "I'm so glad to see you.",
    "What's your favorite color?",
    "I can't make it this time, sorry.",
    "I need your advice on something.",
    "Can I give you a hand with that?",
    "Let's go grab a coffee together.",
    "What's the latest news?",
    "I had a delicious meal at that restaurant.",
    "How's your garden looking these days?",
    "I'll make sure to be there on time.",
    "What's your dream vacation destination?",
    "I'm excited for the upcoming event.",
    "What's your favorite season?",
    "I'm not feeling very well today.",
    "I'd love to hear your opinion on this.",
    "Can you believe what happened yesterday?",
    "I'll get back to you with an answer.",
    "How's your day been so far?",
    "I'm really impressed with your work.",
    "I hope everything turns out okay.",
    "What's your favorite place to relax?",
    "I had a blast at the party.",
    "I'm looking forward to the weekend.",
    "How's your morning routine going?",
    "I had a great time with my friends.",
    "I need a break from all this work.",
    "What's your favorite type of food?",
    "I'll be in touch with more details.",
    "I hope you have a safe journey.",
    "What's your favorite holiday?",
    "I'm always here to support you.",
    "I'm here to listen if you want to talk.",
    "How's your home renovation project?",
    "I had an amazing experience last week.",
    "I can't wait to see the results.",
    "Let's make the most of today.",
    "I hope you enjoy your day off.",
    "What's your favorite sport?",
    "I'm glad to have you as a friend.",
    "I'll get started on that right away.",
    "How's your work-life balance?",
    "I'm really excited about this opportunity.",
    "I had a lot of fun at the concert.",
    "I'm going to take a break now.",
    "What's your favorite animal?",
    "I'll be right back, just a moment.",
    "I'm feeling inspired today.",
    "I hope you have a wonderful week ahead.",
    "What's your favorite holiday tradition?",
    "I had a relaxing day at the beach.",
    "I'm sorry for any inconvenience caused.",
    "Let's make the most of our time together.",
    "I'm excited about the new project.",
    "I hope you had a great weekend.",
    "What's your favorite type of dessert?",
    "I'll do my best to help you out.",
    "I'm really looking forward to the holidays.",
    "How's your fitness journey going?",
    "I had a productive day at work.",
    "I'm here to offer my support.",
    "I hope you have a great evening.",
    "What's your favorite childhood memory?",
    "I'll check my schedule and get back to you.",
    "I'm feeling a bit overwhelmed right now.",
    "I had a wonderful time on vacation.",
    "I'm so grateful for your help.",
    "What's your favorite hobby to unwind?",
    "I'll keep you updated on the progress.",
    "I'm ready to tackle this challenge.",
    "I hope you're enjoying your meal.",
    "How's your weekend shaping up?",
    "I had a long day at the office.",
    "I'm always here to lend an ear.",
    "What's your favorite type of art?",
    "I'll make sure to double-check the details.",
    "I'm excited to see your new place.",
    "I hope you have a peaceful night.",
    "What's your favorite book genre?",
    "I had a great time exploring the city.",
    "I'm ready to face whatever comes my way.",
    "I hope you have a successful presentation.",
    "What's your favorite way to relax?",
    "I'll be there to support you all the way.",
    "I'm looking forward to our next adventure.",
    "I hope you have a wonderful birthday.",
    "How's your week going so far?",
    "I had a fantastic time at the party.",
    "I'm here to lend a helping hand.",
    "What's your favorite type of movie?",
    "I'll be there to cheer you on.",
    "I'm excited about our future plans.",
    "I hope you have a relaxing evening.",
    "What's your favorite vacation memory?",
    "I had a great workout today.",
    "I'm here to share in your happiness.",
    "I'll be sure to keep you informed.",
    "I'm ready to take on new challenges.",
    "I hope you have a productive day.",
    "What's your favorite way to de-stress?",
    "I'll be sure to bring dessert to dinner.",
    "I'm looking forward to our next meeting.",
    "I hope you have a fantastic week.",
    "How's your day looking so far?",
    "I had a fun time at the amusement park.",
    "I'm here to provide guidance and support.",
    "What's your favorite type of coffee?",
    "I'll be there to celebrate with you.",
    "I'm excited about the new chapter in life.",
    "I hope you have a peaceful morning.",
    "What's your favorite quote?",
    "I had a great time at the art gallery.",
    "I'm here to offer encouragement and motivation.",
    "I'll be sure to bring my favorite dish.",
    "I'm looking forward to our next adventure.",
    "I hope you have a relaxing day.",
    "What's your favorite board game?",
    "I had a successful day at work.",
    "I'm here to lend a sympathetic ear.",
    "I'll be there to share the joy with you.",
    "I'm excited about the opportunities ahead.",
    "I hope you have a wonderful evening.",
    "What's your favorite childhood toy?",
    "I had a lovely day at the park.",
    "I'm here to provide reassurance and comfort.",
    "I'll be sure to arrive early for the event.",
    "I'm looking forward to our next challenge.",
    "I hope you have a great night.",
    "What's your favorite song?",
    "I had a relaxing day at the spa.",
    "I'm here to offer my heartfelt congratulations.",
    "What's your favorite travel destination?",
    "I'll be there to support you in your journey.",
    "I'm excited about your achievements.",
    "I hope you have a fantastic morning."
  ]


end
