class DataFile

  # Thanks ChatGpt for providing names for me, despite resisting and trying to convonce me to use Faker

  $male_names = [
    "Adam", "Aiden", "Alex", "Alexander", "Andrew", "Anthony", "Archer", "Asher", "Benjamin", "Caleb", "Cameron",
    "Carter", "Charles", "Christopher", "Daniel", "David", "Declan", "Dominic", "Eli", "Elias", "Elijah", "Eliott",
    "Emmett", "Ethan", "Everett", "Felix", "Gabriel", "George", "Henry", "Hudson", "Hunter", "Isaac", "Jack", "Jackson",
    "Jacob", "James", "Jason", "John", "Jonathan", "Joseph", "Joshua", "Josiah", "Julian", "Kaden", "Landon", "Leo",
    "Liam", "Lincoln", "Logan", "Lucas", "Mason", "Matthew", "Maxwell", "Michael", "Nathan", "Nicholas", "Noah", "Oliver",
    "Oscar", "Owen", "Patrick", "Samuel", "Sebastian", "Theodore", "Thomas", "Tristan", "Victor", "William", "Wyatt",
    "Xander", "Zachary", "Zane", "Aleksandr", "Andrey", "Antono", "Artem", "Dmitri", "Fedor", "Ivan", "Kirill",
    "Konstantin", "Maksim", "Mikhail", "Nikita", "Nikolay", "Pavel", "Sergey", "Stanislav", "Vadim", "Viktor", "Vladimir",
    "Yuriont", "Aleksandron", "Alexeiko", "Anatoli", "Andrei", "Anton", "Arkadi", "Boris", "Dmitrii", "Evgenii", "Fyodor",
    "Grigori", "Igor", "Ilya", "Leonid", "Mikhailos", "Nikolai", "Pavelo", "Pyotr", "Sergei", "Viktorn", "Vladimiro", "Yuriis",
    "Yuriy", "Yury"
  ]

  $female_names = [
    "Magdalina", "Abigail", "Ada", "Adriana", "Aisha", "Alejandra", "Alexandra", "Alice", "Alina", "Alicia", "Amelia", "Ana",
    "Anastasia", "Angelina", "Anna", "Annabelle", "Aria", "Ariana", "Aurora", "Ava", "Bella", "Brianna", "Camila",
    "Caroline", "Charlotte", "Chloe", "Clara", "Cora", "Daisy", "Eleanor", "Elena", "Eliza", "Elizabeth", "Ella",
    "Emilia", "Emily", "Emma", "Eva", "Evelyn", "Faith", "Fiona", "Gabriela", "Grace", "Hannah", "Harper", "Hazel",
    "Isabella", "Ivy", "Jasmine", "Josephine", "Julia", "Katherine", "Layla", "Leah", "Lena", "Lillian", "Lily", "Luna",
    "Lydia", "Mackenzie", "Madeline", "Madison", "Makayla", "Mila", "Natalie", "Nora", "Olivia", "Paisley", "Penelope",
    "Piper", "Riley", "Ruby", "Samantha", "Savannah", "Scarlett", "Serenity", "Sofia", "Sophia", "Sophie", "Stella",
    "Valentina", "Victoria", "Violet", "Zoe", "Anastazia", "Daria", "Ekaterina", "Eleina", "Elizaveta", "Galina", "Irina",
    "Ksenia", "Larisa", "Ludmila", "Margarita", "Maria", "Nadezhda", "Natalia", "Olga", "Polina", "Svetlana", "Tatiana",
    "Valeintina", "Varvara", "Vera", "Veronika", "Viktoria", "Yelena", "Aaliyah", "Adalynn", "Adele", "Adrienne", "Alexia",
    "Aliyah", "Amelie", "Angelica", "Arabella", "Beatrice", "Bianca", "Camille", "Catalina", "Cecilia", "Celeste",
    "Delilah", "Evangeline", "Francesca", "Genevieve", "Gianna", "Guinevere", "Haven", "Imogen", "Isabeau", "Jocelyn",
    "Kamila", "Karina", "Katrina", "Leonora", "Liliana", "Luciana", "Luz", "Mallory", "Margot", "Marina", "Melody",
    "Miranda", "Nadia", "Nayeli", "Noelle", "Ophelia", "Rosalie", "Seraphina", "Sienna", "Sylvia", "Talia", "Viviana",
    "Wren", "Zara"
  ]

  $conversational_phrases = [
    "How's it going?",
    "What's up?",
    "Nice weather we're having, isn't it?",
    "How was your day?",
    "What are your plans for the weekend?",
    "I'm sorry to hear that.",
    "Congratulations on your success!",
    "I appreciate your help.",
    "Could you please pass the salt?",
    "I'm really looking forward to it.",
    "How's your family doing?",
    "Have you been on any vacations recently?",
    "Do you have any recommendations for a good restaurant?",
    "I can't believe it's already Friday!",
    "What's your favorite book?",
    "I'm feeling a bit under the weather.",
    "Thank you for your time and effort.",
    "It's a pleasure to meet you.",
    "I completely understand.",
    "What's your favorite type of music?",
    "I'll be there in a few minutes.",
    "How's your job going?",
    "What's your favorite movie?",
    "I'm not sure about that.",
    "Can you help me with this?",
    "Let's catch up soon!",
    "I hope you have a great day!",
    "What's your favorite hobby?",
    "What do you like to do in your free time?",
    "I'm here if you need anything.",
    "How's your pet doing?",
    "I had a wonderful weekend.",
    "I'd love to hear more about it.",
    "I'm feeling much better now.",
    "I had a fantastic time last night.",
    "How's your new project coming along?",
    "I'm so glad to see you.",
    "What's your favorite color?",
    "I can't make it this time, sorry.",
    "I need your advice on something.",
    "Can I give you a hand with that?",
    "Let's go grab a coffee together.",
    "What's the latest news?",
    "I had a delicious meal at that restaurant.",
    "How's your garden looking these days?",
    "I'll make sure to be there on time.",
    "What's your dream vacation destination?",
    "I'm excited for the upcoming event.",
    "What's your favorite season?",
    "I'm not feeling very well today.",
    "I'd love to hear your opinion on this.",
    "Can you believe what happened yesterday?",
    "I'll get back to you with an answer.",
    "How's your day been so far?",
    "I'm really impressed with your work.",
    "I hope everything turns out okay.",
    "What's your favorite place to relax?",
    "I had a blast at the party.",
    "I'm looking forward to the weekend.",
    "How's your morning routine going?",
    "I had a great time with my friends.",
    "I need a break from all this work.",
    "What's your favorite type of food?",
    "I'll be in touch with more details.",
    "I hope you have a safe journey.",
    "What's your favorite holiday?",
    "I'm always here to support you.",
    "I'm here to listen if you want to talk.",
    "How's your home renovation project?",
    "I had an amazing experience last week.",
    "I can't wait to see the results.",
    "Let's make the most of today.",
    "I hope you enjoy your day off.",
    "What's your favorite sport?",
    "I'm glad to have you as a friend.",
    "I'll get started on that right away.",
    "How's your work-life balance?",
    "I'm really excited about this opportunity.",
    "I had a lot of fun at the concert.",
    "I'm going to take a break now.",
    "What's your favorite animal?",
    "I'll be right back, just a moment.",
    "I'm feeling inspired today.",
    "I hope you have a wonderful week ahead.",
    "What's your favorite holiday tradition?",
    "I had a relaxing day at the beach.",
    "I'm sorry for any inconvenience caused.",
    "Let's make the most of our time together.",
    "I'm excited about the new project.",
    "I hope you had a great weekend.",
    "What's your favorite type of dessert?",
    "I'll do my best to help you out.",
    "I'm really looking forward to the holidays.",
    "How's your fitness journey going?",
    "I had a productive day at work.",
    "I'm here to offer my support.",
    "I hope you have a great evening.",
    "What's your favorite childhood memory?",
    "I'll check my schedule and get back to you.",
    "I'm feeling a bit overwhelmed right now.",
    "I had a wonderful time on vacation.",
    "I'm so grateful for your help.",
    "What's your favorite hobby to unwind?",
    "I'll keep you updated on the progress.",
    "I'm ready to tackle this challenge.",
    "I hope you're enjoying your meal.",
    "How's your weekend shaping up?",
    "I had a long day at the office.",
    "I'm always here to lend an ear.",
    "What's your favorite type of art?",
    "I'll make sure to double-check the details.",
    "I'm excited to see your new place.",
    "I hope you have a peaceful night.",
    "What's your favorite book genre?",
    "I had a great time exploring the city.",
    "I'm ready to face whatever comes my way.",
    "I hope you have a successful presentation.",
    "What's your favorite way to relax?",
    "I'll be there to support you all the way.",
    "I'm looking forward to our next adventure.",
    "I hope you have a wonderful birthday.",
    "How's your week going so far?",
    "I had a fantastic time at the party.",
    "I'm here to lend a helping hand.",
    "What's your favorite type of movie?",
    "I'll be there to cheer you on.",
    "I'm excited about our future plans.",
    "I hope you have a relaxing evening.",
    "What's your favorite vacation memory?",
    "I had a great workout today.",
    "I'm here to share in your happiness.",
    "I'll be sure to keep you informed.",
    "I'm ready to take on new challenges.",
    "I hope you have a productive day.",
    "What's your favorite way to de-stress?",
    "I'll be sure to bring dessert to dinner.",
    "I'm looking forward to our next meeting.",
    "I hope you have a fantastic week.",
    "How's your day looking so far?",
    "I had a fun time at the amusement park.",
    "I'm here to provide guidance and support.",
    "What's your favorite type of coffee?",
    "I'll be there to celebrate with you.",
    "I'm excited about the new chapter in life.",
    "I hope you have a peaceful morning.",
    "What's your favorite quote?",
    "I had a great time at the art gallery.",
    "I'm here to offer encouragement and motivation.",
    "I'll be sure to bring my favorite dish.",
    "I'm looking forward to our next adventure.",
    "I hope you have a relaxing day.",
    "What's your favorite board game?",
    "I had a successful day at work.",
    "I'm here to lend a sympathetic ear.",
    "I'll be there to share the joy with you.",
    "I'm excited about the opportunities ahead.",
    "I hope you have a wonderful evening.",
    "What's your favorite childhood toy?",
    "I had a lovely day at the park.",
    "I'm here to provide reassurance and comfort.",
    "I'll be sure to arrive early for the event.",
    "I'm looking forward to our next challenge.",
    "I hope you have a great night.",
    "What's your favorite song?",
    "I had a relaxing day at the spa.",
    "I'm here to offer my heartfelt congratulations.",
    "What's your favorite travel destination?",
    "I'll be there to support you in your journey.",
    "I'm excited about your achievements.",
    "I hope you have a fantastic morning."
  ]

  $bios = [
    "Explorer of new cuisines, lover of jazz, and avid hiker. Seeking someone who appreciates a good adventure.",
    "Early bird and a marathon runner. I believe in seizing the day and making every pancake count!",
    "Bookworm, tea enthusiast, and lover of rainy days. Let's swap book recommendations and stories.",
    "Amateur guitarist, professional cat whisperer. Let’s talk about your favorite tune and pet stories.",
    "Board game strategist, trivia aficionado, and seeker of the best coffee spots in town.",
    "Plant parent, yoga enthusiast, and believer in kindness. Let’s grow together in all aspects of life.",
    "Stargazer, poet, and spontaneous road-tripper. Excited to find someone to share in the wonder.",
    "Film buff, aspiring chef, and occasional painter. Let's share our creative passions and inspirations.",
    "Tech-savvy, fitness-oriented, with a passion for podcasts. Let's exchange our favorite episodes.",
    "Globe-trotter, language learner, and photography hobbyist. Seeking a partner to capture life's moments.",
    "Avid reader, salsa dancer, and curious chef. Looking for someone who's ready to turn the page with me.",
    "Passionate about sustainable living, DIY projects, and jazz music. Let’s make the world greener together.",
    "Lifelong learner, documentary buff, and volunteer. Seeking meaningful conversations and laughter.",
    "Adventurous soul, puzzle solver, and lover of the sea. Seeking a co-captain for life's voyages.",
    "Tech enthusiast, indie game lover, and podcast addict. Let's share our favorite tech hacks and laughs.",
    "Urban explorer, mural photographer, and taco Tuesday expert. Looking for a fellow flavor seeker.",
    "Yoga practitioner, smoothie specialist, and sunrise chaser. Let's find our zen and fun.",
    "Dedicated runner, coffee connoisseur, and journal keeper. Let’s share morning routines and dreams.",
    "Thrill-seeker, skydiver, and occasional poet. Let's find our adrenaline rush and quiet moments.",
    "Aspiring polyglot, chess player, and world traveler. Let’s share languages and checkmates.",
    "Hopeless romantic, vintage collector, and proud plant parent. Seeking a timeless love and conversation.",
    "Craft beer enthusiast, local band supporter, and karaoke champion. Let's find our perfect duet.",
    "Backpacker, climber, and environmentalist. Seeking a partner for trails and talks about sustainability.",
    "Culinary adventurer, history buff, and theatre-goer. Seeking a co-star for life’s dramas and comedies.",
    "Cycling fanatic, tech tinkerer, and vinyl record hunter. Let's share our tunes and trails.",
    "Creative writer, crossword wizard, and lover of old movies. Looking for a plot twist and a partner in crime.",
    "Homebrewer, fantasy football manager, and amateur astronomer. Seeking a star to align with.",
    "Nature lover, animal rescuer, and advocate for kindness. Let’s make a difference together.",
    "Comedy club regular, improv performer, and meme curator. Looking for laughs and spontaneity.",
    "Dedicated foodie, fermentation fan, and hot yoga attendee. Seeking a partner in health and flavor.",
    "Minimalist, zen gardener, and haiku composer. Seeking simplicity and depth in connection.",
    "Quirky, animated, and an eternal optimist. Let's color outside the lines together.",
    "Gadget collector, sci-fi enthusiast, and weekend hiker. Looking for someone to share in my adventures.",
    "Beach volleyball amateur, smooth jazz lover, and aspiring brewmaster. Let’s play, relax, and create.",
    "Sustainable traveler, thrift shop explorer, and amateur painter. Seeking a canvas companion.",
    "Meditation guide, social entrepreneur, and poetry slam fan. Seeking a partner in mindfulness and creativity.",
    "Urban farmer, fermentation enthusiast, and blues music aficionado. Let’s cultivate a connection.",
    "Stargazing aficionado, environmental advocate, and electric car enthusiast. Looking for a sustainable spark.",
    "DIY furniture maker, aspiring potter, and podcast junkie. Seeking a fellow creator and conversationalist.",
    "Weekend cyclist, fresh pasta maker, and digital nomad. Seeking a companion for the road, both online and off.",
    "Perpetual student, language lover, and ethical hacker. Let’s share knowledge and curiosity.",
    "Social butterfly, karaoke star, and community theater actor. Looking for a partner to share the spotlight.",
    "Vintage vinyl collector, swing dancer, and classic car restorer. Seeking a timeless connection.",
    "Eco-conscious fashion designer, vegan baker, and spoken word artist. Let’s design a better world together.",
    "Outdoor enthusiast, conservation volunteer, and bird watcher. Seeking a fellow nature lover.",
    "Gourmet chef, wine taster, and travel photographer. Let’s explore the world one bite at a time.",
    "Graphic novelist, retro gamer, and skateboarder. Looking for a fellow adventurer, on and off the page.",
    "Aquarium hobbyist, marine life lover, and scuba diver. Seeking a partner for deep dives and deeper conversations.",
    "Pragmatic programmer, AI hobbyist, and virtual reality explorer. Seeking a co-developer for life’s code.",
    "Silent retreat fan, mindfulness coach, and herbal tea collector. Let’s connect on a deeper level.",
    "Kite surfer, beach jogger, and tropical fruit enthusiast. Looking for a breezy conversation and sunny smiles.",
    "Personal trainer, health blogger, and sunrise jogger. Seeking someone to share the path to wellness.",
    "Real estate mogul in training, architecture enthusiast, and house-flipper. Seeking a foundation for growth.",
    "Occult historian, tarot reader, and candle maker. Seeking someone who appreciates the mystical side of life.",
    "Origami artist, puzzle enthusiast, and stop-motion animator. Let’s create life’s tapestry together.",
    "Hiking guide, wilderness first responder, and organic gardener. Seeking a partner for life’s trails.",
    "Microbrewery owner, hop grower, and live music lover. Looking for a fellow artisanal spirit.",
    "Historical reenactor, antique restorer, and period drama buff. Seeking a partner to turn back time with.",
    "Sleep researcher, lucid dreamer, and nighttime tea drinker. Let’s share dreams and reality.",
    "Sushi rolling expert, sumo wrestling fan, and Japanese language student. Seeking a partner to roll with the punches.",
    "Off-grid living aspirant, renewable energy advocate, and tiny home builder. Seeking someone to share my eco-dream.",
    "Disco roller-skater, 80s music collector, and neon art creator. Looking for a retro romance.",
    "Firefighter, risk-taker, and first aid trainer. Seeking someone to ignite a flame that won’t burn out.",
    "Solar system model builder, amateur astrophotographer, and planetarium frequenter. Seeking a stellar companion.",
    "Intuitive painter, abstract thinker, and mural lover. Let’s paint a colorful life together.",
    "Upcycling artist, thrift shop hunter, and creative writer. Seeking an imaginative soul.",
    "Stand-up comedian, sitcom writer, and pun champion. Looking for someone who loves a good laugh.",
    "Public speaker, debate club champ, and non-profit organizer. Seeking a conversation that never dulls.",
    "Mountain biker, rock climber, and campfire storyteller. Seeking a partner for the peaks and valleys.",
    "Chocolatier, dessert blogger, and sweet tooth owner. Seeking someone sweet and a little bit decadent.",
    "Cold brew sipper, startup founder, and idea generator. Looking for a brainstorm buddy.",
    "Botanical illustrator, rare plant collector, and succulent grower. Seeking someone to help water the seeds of love.",
    "Time capsule creator, 90s nostalgia buff, and vintage camera collector. Seeking someone for timeless memories.",
    "Astrologer, moon phase tracker, and crystal collector. Seeking a partner to align with the stars.",
    "Peace corps volunteer, humanitarian, and world peace advocate. Looking for a heart of gold.",
    "Multi-instrumentalist, symphony volunteer, and lover of all things musical. Seeking a duet partner.",
    "Trail runner, obstacle course racer, and mud run enthusiast. Seeking a partner to get dirty with in life.",
    "Home cook, meal prepper, and family recipe collector. Looking for someone to spice up my life.",
    "Acroyoga participant, slackline walker, and functional fitness coach. Seeking balance in life and love.",
    "Conspiracy theorist, secret society researcher, and documentary maker. Let’s uncover the truths of life together.",
    "Special effects makeup artist, horror film fanatic, and haunted house reviewer. Seeking a scream-worthy connection.",
    "Modern nomad, van lifer, and national park explorer. Seeking someone to share the roadmap of life.",
    "Mechanical keyboard builder, custom PC maker, and ergonomic enthusiast. Seeking a key to unlock new memories.",
    "Artisanal soap maker, bath bomb blender, and aroma therapy student. Seeking someone to soak up life with.",
    "Dog agility trainer, pet foster parent, and animal rights activist. Seeking a partner for a pawsome life.",
    "Life coach, motivational podcaster, and sunrise meditator. Looking for someone to rise and shine with.",
    "Feng shui consultant, interior decorator, and home organizer. Seeking someone to create harmony with.",
    "Archaeology dig volunteer, history museum member, and ancient civilizations buff. Seeking a timeless connection.",
    "Virtual reality game designer, 3D modeler, and esports fan. Seeking a player two for the game of life.",
    "Hang gliding pilot, paragliding enthusiast, and lover of heights. Seeking someone to soar with."
  ]

end
